spring:
    datasource:
        url: jdbc:postgresql://localhost:5432/skillspace-db
        username: myuser
        password: mypassword
        driver-class-name: org.postgresql.Driver

    data:
        redis:
            host: localhost
            port: 6379

    application:
        name: skillspace-backend
    
    jpa:
        hibernate:
            ddl-auto: none
        show-sql: false
        database-platform: org.hibernate.dialect.PostgreSQLDialect
logging:
    level:
        org:
            hibernate:
                SQL: OFF
                type:
                    descriptor:
                        sql:
                            BasicBinder: OFF
spring.flyway:
    enabled: true
    locations: classpath:db/migration
    baseline-description: true